# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_mark_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='final_mark',
            field=models.FloatField(null=True),
        ),
    ]
