# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_auto_20170802_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_id',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
