# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_auto_20170808_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='final_mark',
            field=models.FloatField(default=8),
            preserve_default=False,
        ),
    ]
