# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
