# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_auto_20170726_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='content_html',
            field=models.TextField(blank=True, default='', editable=False),
        ),
    ]
