# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 03:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0003_thread_content_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='thread_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='threadimages',
            name='image',
            field=models.ImageField(upload_to='thread_images/', verbose_name='Image'),
        ),
    ]
