# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0005_auto_20170727_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadimages',
            name='image',
            field=models.ImageField(upload_to='thread_images/'),
        ),
    ]
