# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('student_id', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('private_email', models.EmailField(default='None', max_length=255)),
                ('profile_pic', models.ImageField(default='images/user-default.jpg', upload_to='profile_pics/')),
                ('status', models.CharField(choices=[('ST', 'Studying'), ('GT', 'Graduated'), ('AD', 'Admintrator')], default='ST', max_length=2)),
                ('date_of_birth', models.DateField(default='2017-01-01', max_length=8)),
                ('gender', models.BooleanField(default=True)),
                ('joined_time', models.DateField(auto_now=True)),
                ('graduated_year', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('home_address', models.CharField(max_length=256)),
                ('mobile_phone', models.CharField(max_length=12, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'StudentProfiles',
            },
        ),
    ]
