# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 01:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170724_0642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='std_id',
            new_name='student_id',
        ),
    ]
