# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170725_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(default='2017-01-01', max_length=8),
        ),
    ]
