# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170726_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='home_address',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='mobile_phone',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='private_email',
            field=models.EmailField(blank=True, default='', max_length=255, null=True),
        ),
    ]
