# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_studentprofile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.BooleanField(default=True),
        ),
    ]
