# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_studentprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_pic',
            field=models.ImageField(default='images/user-default.jpg', upload_to='profile_pics/'),
        ),
    ]
