# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170725_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='graduated_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='joined_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
