# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170725_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='mobile_phone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
