# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20170725_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='private_email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
