# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_studentprofile_private_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='private_email',
            field=models.EmailField(default='None', max_length=255),
        ),
    ]
