# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subforum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('short_name', models.CharField(max_length=20)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subforum', to='subjects.Subject')),
            ],
            options={
                'db_table': 'Subforums',
            },
        ),
    ]
