# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subforums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='thread_pics/')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='subforums.Thread')),
            ],
        ),
    ]
