# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subforums', '0002_threadimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='subforum',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
