# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subforums', '0003_subforum_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='title',
            field=models.CharField(default='', max_length=350),
            preserve_default=False,
        ),
    ]
